if(!dir.exists('processedData')) dir.create('processedData')
if(!dir.exists('results')) dir.create('results')
if(!dir.exists('results/miniResults')) dir.create('results/miniResults')
if(!dir.exists('figure')) dir.create('figure')
if(!dir.exists('tables')) dir.create('tables')
